from enum import Enum


class ProcessTypes(Enum):
    DNA_RNA = "AFEM_PARAMETERS"
    PROTEIN = "AFEM_PARAMETERS"
    WITH_NUMERICAL_MAPPING_DNA_RNA = "AFEM_PARAMETERS"
    BINARY_PROBLEMS = "METALEARNING_PARAMETERS"
    MULTICLASS_PROBLEMS = "METALEARNING_PARAMETERS"
