name: Build and Deploy Image

on:
  push:
    branches: [ "main" ]

jobs:

  build-application:
    name: Build and Deploy Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./
        push: true
        tags: bioautoml/job:latest, bioautoml/job:${{ github.sha }}
        
  deploy:
    name: Deploy app
    needs: build-application
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker pull bioautoml/job:latest
          docker container stop bioautoml-job
          docker container rm bioautoml-job
          docker container run --detach --name bioautoml-job -e APP_AMQP_ADDRESS=${{ secrets.AMQP_ADDRESS }} -e APP_WORKERS=${{ secrets.APP_WORKERS }} bioautoml/job:latest
    

    
