name: Deploy APP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
      name: Deploy Onpremise
      runs-on: ubuntu-latest

      steps:
        - name: Connect Onpremise and Run Commands
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.VPS_HOST }}
            username: ${{ secrets.VPS_USER }}
            port: ${{ secrets.VPS_PORT }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              cd ~
              git clone https://github.com/FeCesar/bioautoml-job.git
              cd bioautoml-job
              git pull
              cd ~
              rm -rf /etc/environment
              LC_ALL=en_US.UTF-8 >> /etc/environment
              APP_AMQP_ADDRESS=${{ secrets.AMQP_ADDRESS }} >> /etc/environment
              APP_WORKERS=${{ secrets.APP_WORKERS }} >> /etc/environment
              APP_RCLONE_EXTRACT_FILES_FOLDER_PATH=${{ secrets.APP_RCLONE_EXTRACT_FILES_FOLDER_PATH }} >> /etc/environment
              APP_BIOAUTOML_PATH=${{ secrets.APP_BIOAUTOML_PATH }} >> /etc/environment
              APP_OUTPUT_FILES=${{ secrets.APP_OUTPUT_FILES }} >> /etc/environment
              APP_MINICONDA_PATH=${{ secrets.APP_MINICONDA_PATH }} >> /etc/environment
              APP_LOGGER_LEVEL=INFO >> /etc/environment
              bash ~/bioautoml-job/setup.sh