name: Deploy APP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
      name: Deploy Onpremise
      runs-on: ubuntu-latest

      steps:
        - name: Connect Onpremise and Run Commands
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.VPS_HOST }}
            username: ${{ secrets.VPS_USER }}
            port: ${{ secrets.VPS_PORT }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              cd ~
              git clone https://github.com/FeCesar/bioautoml-job.git
              cd bioautoml-job
              git pull
              cd ~
              rm -rf ~/bioautoml-job/.env
              echo "APP_AMQP_ADDRESS=${{ secrets.AMQP_ADDRESS }}" >> ~/bioautoml-job/.env
              echo "APP_WORKERS=${{ secrets.APP_WORKERS }}" >> ~/bioautoml-job/.env
              echo "APP_RCLONE_EXTRACT_FILES_FOLDER_PATH=${{ secrets.APP_RCLONE_EXTRACT_FILES_FOLDER_PATH }}" >> ~/bioautoml-job/.env
              echo "APP_BIOAUTOML_PATH=${{ secrets.APP_BIOAUTOML_PATH }}" >> ~/bioautoml-job/.env
              echo "APP_OUTPUT_FILES=${{ secrets.APP_OUTPUT_FILES }}" >> ~/bioautoml-job/.env
              echo "APP_MINICONDA_PATH=${{ secrets.APP_MINICONDA_PATH }}" >> ~/bioautoml-job/.env
              echo "APP_RCLONE_CONFIG_PATH=${{ secrets.APP_RCLONE_CONFIG_PATH }}" >> ~/bioautoml-job/.env
              echo "APP_LOGGER_LEVEL=INFO" >> ~/bioautoml-job/.env
              rm -rf ~/.config/rclone/rclone.conf
              echo "[s3]" >> ~/.config/rclone/rclone.conf
              echo "type = s3" >> ~/.config/rclone/rclone.conf
              echo "provider = AWS" >> ~/.config/rclone/rclone.conf
              echo "env_auth = false" >> ~/.config/rclone/rclone.conf
              echo "access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.config/rclone/rclone.conf
              echo "secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.config/rclone/rclone.conf
              echo "region = us-east-1" >> ~/.config/rclone/rclone.conf
              echo "endpoint =" >> ~/.config/rclone/rclone.conf
              echo "location_constraint =" >> ~/.config/rclone/rclone.conf
              echo "acl = private" >> ~/.config/rclone/rclone.conf
              echo "server_side_encryption =" >> ~/.config/rclone/rclone.conf
              echo "storage_class =" >> ~/.config/rclone/rclone.conf
              nohup bash ~/bioautoml-job/setup.sh &
